[package]
name = "tmsql"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
regex = "1.5"
csv = "1.1.6"
rusqlite = "0.25.3"
serde = { version = "1", features = ["derive"] }
